export interface Listing {
  id?: string;
  title: string;
  description?: string;
  price: number;
  rentAdvance?: number;
  rentAdvanceMonths?: number;
  bedrooms?: number;
  bathrooms?: number;
  size?: number;
  type?: string;
  propertyType?: string;
  buildingType?: string;
  location: string;
  photos: string[]; // Cloudinary image URLs
  userId?: string;
  landlordId?: string;
  region?: string;
  verified?: boolean;
  featured?: boolean;
  premium?: boolean;
  amenities?: string[];
  available?: boolean;
  availabilityDate?: string;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  contactWhatsApp?: string;
  coverPhoto?: string;
  securityDeposit?: number;
  additionalFeatures?: string;
  status?: 'pending' | 'active' | 'archived';
  createdAt?: string | null;
  updatedAt?: string | null;
  reportedCount?: number;
  landmark?: string;
  securityLevel?: 'High' | 'Moderate' | 'Low';
  securityFeatures?: string[];
  electricityType?: 'Prepaid' | 'Postpaid';
  electricityRange?: string;
  waterAvailability?: 'Regular' | 'Irregular' | 'Not available';
  noiseLevel?: 'Quiet' | 'Moderate' | 'Noisy';
  roadCondition?: 'Tiled' | 'Gravel' | 'Rough' | 'Very bad';
  category?: string;
  geoPoint?: { lat: number; lng: number };
  directionsEnabled?: boolean;
  advancePaymentNumber?: string;
}